# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load an ABF2 file
#' 
#' @param path Path to the file
#' @export
abf2load <- function(path) {
    .Call(`_abf2loader_abf2load`, path)
}

